### ISSUE TITLE
Example Not working

### ISSUE THREAD

**Issue by himanshu-itmca** [dpa99c/cordova-plugin-firebasex-ionic3-test#1]
11-14 19:34:07.049 31509 31509 I chromium: [INFO:CONSOLE(34)] "ERROR TypeError: Cannot read property 'getToken' of undefined", source: ng:///AppModule/HomePage.ngfactory.js (34)

**Comment by dpa99c** [comment]
This is not enough information to diagnose an issue.
This example works fine for me on both iOS and Android platforms.
Note it will not work in the browser environment (`ionic serve`) as this is not supported by the plugin.
