### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by zinebAme** [dpa99c/cordova-plugin-firebasex-ionic3-test#2]
I did install the app in my phone android and it's not working.

**Comment by dpa99c** [comment]
This is insufficient information to open an issue. Please complete the issue template and provide full details if reporting an issue.

Note that this project is only an illustration of how the JS plugin API can be used with Ionic 3, not a complete test project which covers the full plugin functionality - for this please build and run https://github.com/dpa99c/cordova-plugin-firebasex-test
